import json
import os
import re


def to_camel_case(string):
    result = ""
    for word in re.sub("[^0-9a-zA-Z]", " ", string).split():
        if result == "":
            result += word.lower()
        elif len(word) == 2 and word == word.upper():  # if two letter acronym
            result += word
        else:
            result += word.lower().capitalize()
    return result


code = ""

with open("DeviceSettings.json") as json_file:
    json_array = json.load(json_file)
    for json_object in json_array:

        # Section
        temp_section = json_object["name"]

        for word in re.sub("[^0-9a-zA-Z]", " ", temp_section).split():
            if word.isupper():
                temp_section = temp_section.replace(word, "\\acs{" + word + "}")

        # Type
        temp_type = "number"

        for declaration in {"char name[", "RS9116IPAddress", "RS9116MacAddress"}:
            if declaration in json_object["declaration"]:
                temp_type = "string"

        if "bool" in json_object["declaration"]:
            temp_type = "true or false"

        # Default
        temp_default = json_object["default"].replace("{", "").replace("}", "")

        if "\"" in temp_default:
            temp_default = "\\enquote{" + temp_default.replace("\"", "") + "}"

        # Read-only
        try:
            calibration = json_object["calibration"]
        except:
            calibration = False
        try:
            read_only = json_object["read only"]
        except:
            read_only = False | calibration

        if read_only:
            read_only_string = " (read-only)"
        else:
            read_only_string = ""

        # Create TEX
        camel_case_name = to_camel_case(json_object["name"])

        code += "\n\\begingroup\n"
        code += "    \\def\\tempSection{" + temp_section + read_only_string + "}\n"
        code += "    \\def\\tempLabel{sec:" + camel_case_name + "}\n"
        code += "    \\def\\tempDescription\n    {\n        " + temp_section.replace("\\acs", "\\ac") + ".\n    }\n"
        code += "    \\def\\tempKey{" + camel_case_name + "}\n"
        code += "    \\def\\tempType{" + temp_type + "}\n"
        code += "    \\def\\tempDefault{" + temp_default + "}\n"
        code += "    \\deviceSetting\n"
        code += "\\endgroup\n"

with open("individualSettings.tex", "w") as tex_file:
    tex_file.write("% This file was generated by " + os.path.basename(__file__) + "\n")
    tex_file.write(code)
